<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Go on a Date?</title>
  <style>
    body {
      font-family: 'Arial', sans-serif;
      margin: 0;
      padding: 0;
      height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
      background: linear-gradient(135deg, #ff9a9e, #fad0c4, #fbc2eb);
      animation: gradient 8s ease infinite;
      overflow: hidden;
    }

    @keyframes gradient {
      0% { background-position: 0% 50%; }
      50% { background-position: 100% 50%; }
      100% { background-position: 0% 50%; }
    }

    .container {
      text-align: center;
      position: relative;
      z-index: 1;
      padding: 0 20px; /* For better layout on small screens */
    }

    h1 {
      font-size: 2rem;
      color: white;
      text-shadow: 2px 2px 4px rgba(0, 0, 0, 0.6);
      margin-bottom: 20px;
    }

    .buttons {
      position: relative;
      display: inline-block;
      width: 300px;
      height: 150px;
    }

    button {
      padding: 12px 25px;
      font-size: 1rem;
      font-weight: bold;
      border: none;
      border-radius: 50px;
      cursor: pointer;
      position: absolute;
      transition: transform 0.3s ease, background-color 0.3s ease;
    }

    button:hover {
      transform: scale(1.1);
    }

    .yes {
      background-color: #ff4b5c;
      color: white;
      box-shadow: 0 4px 8px rgba(255, 75, 92, 0.6);
      left: 50%;
      top: 50%;
      transform: translate(-50%, -50%);
    }

    .no {
      background-color: #6c757d;
      color: white;
      box-shadow: 0 4px 8px rgba(108, 117, 125, 0.6);
    }

    /* Popup Overlay */
    .overlay {
      position: fixed;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background: rgba(0, 0, 0, 0.7);
      display: none;
      justify-content: center;
      align-items: center;
      z-index: 10;
    }

    .popup {
      background: white;
      padding: 20px;
      border-radius: 10px;
      box-shadow: 0 4px 10px rgba(0, 0, 0, 0.3);
      text-align: center;
      animation: popup 0.5s ease-out;
      width: 90%;
      max-width: 400px;
    }

    @keyframes popup {
      from {
        transform: scale(0.5);
        opacity: 0;
      }
      to {
        transform: scale(1);
        opacity: 1;
      }
    }

    .popup h2 {
      font-size: 1.8rem;
      margin: 10px 0;
      color: #ff4b5c;
    }

    .popup button {
      margin-top: 15px;
      padding: 10px 20px;
      background: #ff4b5c;
      color: white;
      border: none;
      border-radius: 50px;
      cursor: pointer;
      transition: background-color 0.3s ease;
    }

    .popup button:hover {
      background-color: #e03a4c;
    }
  </style>
</head>
<body>
  <div class="container">
    <h1>Do you want to go on a date with me?</h1>
    <div class="buttons">
      <button class="yes" onclick="showPopup()">Yes</button>
      <button class="no" onmouseover="moveNoButton()">No</button>
    </div>
  </div>

  <!-- Popup Overlay -->
  <div class="overlay" id="popupOverlay">
    <div class="popup">
      <h2>Yay! ❤️</h2>
      <p>I knew you'd say yes! Let's plan something amazing together.</p>
      <button onclick="closePopup()">Close</button>
    </div>
  </div>

  <script>
    function moveNoButton() {
      const noButton = document.querySelector('.no');
      const buttonsContainer = document.querySelector('.buttons');

      // Get dimensions of the container
      const containerWidth = buttonsContainer.offsetWidth;
      const containerHeight = buttonsContainer.offsetHeight;

      const noButtonWidth = noButton.offsetWidth;
      const noButtonHeight = noButton.offsetHeight;

      // Generate random positions within the container
      const randomX = Math.random() * (containerWidth - noButtonWidth);
      const randomY = Math.random() * (containerHeight - noButtonHeight);

      // Apply new position to the "No" button
      noButton.style.left = `${randomX}px`;
      noButton.style.top = `${randomY}px`;
    }

    function showPopup() {
      document.getElementById('popupOverlay').style.display = 'flex';
    }

    function closePopup() {
      document.getElementById('popupOverlay').style.display = 'none';
    }
  </script>
</body>
</html>
